name: Documentation
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout repository
        uses: actions/checkout@v2

      - name: 📥 Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: 📃 Run Docs Generator
        uses: ./.github/actions/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}